---
engines:
  bundler-audit:
    enabled: true
    config:
      path: Gemfile.lock
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  fixme:
    enabled: true
  rubocop:
    enabled: true
  flog:
    enabled: true
  reek:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
exclude_paths:
- test/
